[colors]
background = "#222433"
foreground = "#9ea3c0"
cursor_bg = "#9ea3c0"
cursor_fg = "#222433"
cursor_border = "#9ea3c0"
selection_bg = "#363e7f"
ansi = [
  "#111219",
  "#e58585",
  "#7cbe8c",
  "#8e8a6f",
  "#4c89ac",
  "#6c75cb",
  "#73c1a9",
  "#9ea3c0",
]
brights = [
  "#545c8c",
  "#b871b8",
  "#7cbe8c",
  "#a8a384",
  "#589ec6",
  "#929be5",
  "#59b6b6",
  "#9ea3c0",
]

[metadata]
name = "dogrun"
author = "wadackel"
origin_url = "https://github.com/wadackel/vim-dogrun"
